### ISSUE TITLE
Limitação com a declaração de campos/atributos públicos

### ISSUE THREAD

**Issue by MateusGabi** [Menighin/cei-crawler#1]
Olá, eu detectei um erro que acontece simplesmente executando a biblioteca. Pela minha pequisa eu encontrei na [documentação do Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) que:

> Public and private field declarations are an experimental feature (stage 3) proposed at TC39, the JavaScript standards committee. Support in browsers is limited, but the feature can be used through a build step with systems like Babel.

Talvez por ser experimental esteja ocadionando o erro. Informações abaixo:

Node: `v10.14.2`

Erro:
```
$ node crawler.js     
/home/mgm/dev/puppeteer-cei/node_modules/cei-crawler/src/lib/CeiCrawler.js:9
    _isLogged = false;
              ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

Código:
```
const CeiCrawler = require("cei-crawler");

class Foo {
  async start(email, password) {
    let ceiCrawler = new CeiCrawler(email, password, {
      /* options */
      trace: true
    });

    let stockHistory = await ceiCrawler.getStockHistory();

    console.log(JSON.stringify(stockHistory, undefined, 4));
  }
}

const FooInstance = new Foo();
FooInstance.start("#####", "#####");
```

Eu tenho uma proposta para corrigir: mover para dentro do construtor as declarações. Vou subir um PR.

**Comment by Menighin** [comment]
Oi @MateusGabi obrigado pelo teste e pelo PR.
De fato os private class fields são experimentais e também é possível usá-los no Node 12, que é a versão LTS corrente.

Eu desenvolvi a lib meio na correria pra usar em outro projetinho e o que falta nela de fato é um build mais robusto (ela nem minifica!) que aí talvez a gente possa até transpilar para um código mais compativel, mas eu não gostaria de atualizar o código pra uma versao mais "velha", entende?

É possivel vc usar o Node 12?

Valeu!

**Comment by MateusGabi** [comment]
Opa!

Eu não sabia  que a verão 12 estava disponível. Vou fazer upgrade.

Eu estou há um tempo longe da programação :broken_heart:
