### ISSUE TITLE
Lidar com CPF ou Senha errado

### ISSUE THREAD

**Issue by skepticaldev** [Menighin/cei-crawler#12]
Fala João,

Percebi que quando se coloca um CPF ou Senha errado ele acaba esperando o timeout para dar erro na chamada. Fazendo um teste vi que o site da CEI gera um dialog alertando a respeito do ocorrido. Fazendo umas pesquisas vi o puppeteer não lida automaticamente com dialogs, é preciso lidar dentro do método page.on.

Ex: 
page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
});

Estou tentando implementar mais estou com dificuldade de lidar com os erros disparados dentro de uma função assíncrona.

Acho que seria legal implementar algo para lidar com cpf ou senha errados. Assim não seria preciso esperar até o timeout para retornar o erro.

Abraço!

**Comment by Menighin** [comment]
Opa, boa... Vo tentar implementar algo nesse sentido!

**Comment by Menighin** [comment]
@skepticaldev acabei de lançar a versão `0.3.0` que tem um melhor error handling.
Da uma olhada no README e no Release, pq teve breaking changes.
Vou fechar essa issue mas sinta-se a vontade pra reabrir se ver algo errado.
Valeu pela sugestão 👍

**Comment by skepticaldev** [comment]
Top @Menighin !! Acabei de dar uma olhada lá. Tá Show! Excelente abordagem. Seu código me ajudou muito no meu projeto. Parabéns e obrigado por compartilhar seu conhecimento! Abraço!
