### ISSUE TITLE
getStockHistory: waiting for function failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by cuevas** [Menighin/cei-crawler#24]
Em alguns casos, a função getStockHistory retorna a mensagem 
`waiting for function failed: timeout 30000ms exceeded`

**Comment by Menighin** [comment]
Oi @cuevas , tudo bem?
De fato esse é um problema recorrente do CEI. 
Por vezes ele da timeout, o sistema fica travado numa página. Da minha experiencia, isso acontece mais a noite e fins de semana (não sei se o pessoal lá fica processando algo e pesando o sistema). 
Infelizmente não tem muito o que fazer do lado do `cei-crawler`.
Existe contudo uma opção nos [options](https://github.com/Menighin/cei-crawler#op%C3%A7%C3%B5es) do crawler pra você aumentar ou diminuir esse tempo.
Além disso, você pode [tratar essa exceção](https://github.com/Menighin/cei-crawler#error-handling) e implementar alguma lógica de retry.

**Comment by cuevas** [comment]
Notei que é uma coisa que ocorre muito raramente, vou tratar a exceção como você comentou.
Obrigado pela resposta e parabéns pelo projeto, ficou fantástico!
