### ISSUE TITLE
Problemas com acesso por conta de Captcha do CEI

### ISSUE THREAD

**Issue by ZotInfo** [Menighin/cei-crawler#28]
Opa @Menighin  tudo beleza? Cara tens alguma ideia sobre como burlar o sistema de Captcha que o CEI adicionou? Ou é algo meio impossível de se realizar? hehe

**Comment by Menighin** [comment]
Ou to de férias essa semana e a próxima RS, não vou conseguir olhar... A princípio é um problemão... Talvez o puppeteer facilite nesse caso... 
Em último caso, uma primeira versão poderia promptar o usuário para realizar o login e o crawler seguir automático pra frente... Vô ter que dar uma pesquisada :/

**Comment by LeoCardosoJr** [comment]
Pessoal,

Deem uma olhada https://www.npmjs.com/package/puppeteer-extra-plugin-recaptcha

Isso deve ajudar.

**Comment by felipesdias** [comment]
Aparentemente ele usa um serviço pago para resolver os captcha :(

![image](https://user-images.githubusercontent.com/24731835/98377169-3b8d6b00-2023-11eb-9755-419c0be38517.png)

**Comment by JuniorEC** [comment]
> Aparentemente ele usa um serviço pago para resolver os captcha :(
> 
> ![image](https://user-images.githubusercontent.com/24731835/98377169-3b8d6b00-2023-11eb-9755-419c0be38517.png)

Essa Solução funciona perfeitamente

**Comment by felipesdias** [comment]
Acho que o ideal seria implementar ambos os casos, podendo configurar o token pra usar o 2captcha ou o proprio usuario resolver o captcha com um prompt na tela (muito útil para o stoincs e outras aplicações desktop).

Vou ver se tiro um tempo no final de semana para tentar fazer a implemetação e faço um PR

**Comment by ZotInfo** [comment]
Será que existe alguma maneira de lidar com o Captcha utilizando requisições POST e GET?

**Comment by felipesdias** [comment]
Não fiz uma pesquisa ainda, mas o serviço do reCaptcha é muito bom, tanto que temos varios outros serviços que são pagos para burlar o sistema, talvez algum deles seja possivel resolver com POST/GET.

**Comment by felipesdias** [comment]
Imagino que deva ser possivel sim resolver atraves de GET/POST, mas apenas com o serviço pago, do contrario acho que seria inviavel

**Comment by ZotInfo** [comment]
Opa galera, depois de entrar em contato com o CEI consegui fazer novamente a importação.

Sugiro tentar falar com eles, o suporte foi bem resolvido.

**Comment by felipesdias** [comment]
@ZotInfo não entendi direito, o que vc falou com eles ?

**Comment by ZotInfo** [comment]
@felipesdias foi isso que aconteceu

![image](https://user-images.githubusercontent.com/56548123/98449445-889c3a80-2112-11eb-9b4a-cd5c339fd597.png)

Após esse e-mail eu respondi e ele me passou um outro link para poder acessar

**Comment by felipesdias** [comment]
eles te forneceram um link para realizar o login sem o captcha ?

**Comment by Menighin** [comment]
Pessoal, entrei em contato com a B3 como o @ZotInfo recomendou e me passaram tambem um link que nao faz validação na Catpcha!

Versão `2.1.0` teoricamente está corrigida, qualquer coisa reabram/abram outra issue 👍

**Comment by Rodrizwesley** [comment]
Pessoal, encontrei um outro problema com relação ao acesso ao CEI, estou utilizando essa lib com o NestJs para um trabalho da faculdade e está apresentando o seguinte erro:

[Nest] 18136   - 2020-11-13 12:35:27 AM   [ExceptionsHandler] Cannot read property 'fetch' of null +295302ms
TypeError: Cannot read property 'fetch' of null
    at CeiCrawler._login (\node_modules\cei-crawler\src\lib\CeiCrawler.js:66:56)
    at CeiCrawler.getWallet (\node_modules\cei-crawler\src\lib\CeiCrawler.js:174:20)

Não manjo muito de crawler então não sei o que pode estar acontecendo, qualquer novidade eu aviso a vocês.

**Comment by felipesdias** [comment]
você pode postar a parte do código que usa o cei-crawler, estou achando estranho pois nessa linha não deveria dar esse problema, já que o objeto em que é chamado o fetch foi definido no construtor.

**Comment by Rodrizwesley** [comment]
Bom dia, consegui resolver cara, era uma injeção de dependência no service do meu controller, ainda não entendi de onde saiu esse null mas provavelmente porque o NestJs usa TS deve ser necessário injetar dependência do CeiCrawler no constructor, quando fiz isso funcionou!
