### ISSUE TITLE
Quantidade de acesso

### ISSUE THREAD

**Issue by VictorLessa** [Menighin/cei-crawler#29]
Bom dia amigo, tudo bom?
Existe alguma restrição de acesso na lib? É possível o CEI bloquear minha conta? Você algum solução para isso?
Vi em seu repositório stoincs que você espera a instancia ficar livre, poderia me explicar melhor?

**Comment by Menighin** [comment]
Bom dia Victor,
Desconheço qualquer limitação do lado do CEI que vá levar a algum cenário de bloqueio.
No Stoincs existe a lógica de esperar a instancia terminar uma operação pois antes, quando utilizávamos o Puppetter, ele não lidava bem com paralelismo. Basicamente eu precisava esperar ele abrir e ler as paginas pra depois ir pra outras ou ele se embolava.

Com essa nova versão que o @felipesdias removeu o Puppetteer, pode ser que esse paralelismo não seja mais problema. Não cheguei a testar. No Stoincs eu mantive o código porque já estava feito mesmo.

Abs,

**Comment by VictorLessa** [comment]
Qual a possibilidade de adicionar algum "crawler" do nubank no projeto stoincs?

**Comment by Menighin** [comment]
Hummm como assim? Pra pegar seu saldo no nubank esse tipo de coisa?
Eu nao sei nem se o NuBank tem interface web, tem? Conheço só o aplicativo... E pelo aplicativo nao da pra fazer crawling 🤔

**Comment by Menighin** [comment]
Victor vou fechar a issue aqui porque acredito ter respondido suas duvidas.
Caso tenha algo mais fica a vontade pra postar 👍
