### ISSUE TITLE
Refresh dos cookies

### ISSUE THREAD

**Issue by BrenoAquino** [Menighin/cei-crawler#34]
Boa tarde pessoa,

Eu percebi que os cookies costumam expirar bastante, vocês sabem se existe alguma forma de dar um refresh neles para não perder a sessão? Não gostaria de guardar os dados de usuário/senha, mas não gostaria de que ficasse me pedindo todo dia. Sabem de alguma forma para solucionar esse problema? 

Obrigado pessoal, e o projeto ta massa!

**Comment by felipesdias** [comment]
Boa noite @BrenoAquino ,

Acho que a única forma seria ficar fazendo uma requisição para o CEI, dessa forma "renovando" o tempo de expiração da sessão, mas acredito que essa opção também não seja viável.

Guardar os dados do usuário na sua base de fato é um problemão, talvez seja o caso de criptografar e armazenar no dispositivo do próprio usuário (mas é bom deixar claro para o usuário), dessa forma, ao invés dele ter que entrar com as credencias ele precisar apenas acionar um botão ou até mesmo ser de forma automática.

**Comment by BrenoAquino** [comment]
Não achei outra forma de garantir a sessão do usuário também. Vocês tem alguma ideia qual foi a solução adota por apps como TradeMap? Porque acho invasivo de fato guardar os dados de autenticação do usuário

**Comment by felipesdias** [comment]
Acho invasivo se for guardado no servidor deles, no dispositivo do usuário acho que é relativamente ok (o problema é a segurança, por isso deixar bem claro para o usuário). Do contrário não vejo como garantir a sessão, talvez ficar faZendo pings na api com o cookie pra não deixar ele expirar, mas é uma solução bem trash kkkkk, além de que pode não garantir.

**Comment by Menighin** [comment]
Opa pessoal, tava de férias e nao acompanhei :sweat_smile:

Nao tenho o que acrescentar... Também nao sei alguma forma de manter a sessao...

Vou fechar a issue, caso necessário fica a vontade pra reabrir 👍
