### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by GabrielFelix10** [Menighin/cei-crawler#35]
Bom Dia,

Primeira mente que repositório incrível , que iniciativa fenomenal velho. Parabéns.

Deixa eu perguntar esse crawler funciona mesmo com o recaptcha existente na tela inicial do login do cei ?

**Comment by felipesdias** [comment]
Bom dia,

o CEI fornece um subdomínio para acessar sem o captcha, vc consegue verificar a url dentro do repositório
