### ISSUE TITLE
QR code doação 

### ISSUE THREAD

**Issue by GabrielFelix10** [Menighin/cei-crawler#37]
O QR code pra doação esta quebrando aqui no nu, tava tentando agradecer esse projeto foda que vocês disponibilizaram.

**Comment by Menighin** [comment]
O @GabrielFelix10 fico muito feliz de ver isso hehe
Aquele código é somente do PicPay, vou atualizar e colocar meu PIX tb que pode ser meu email: `joao.menighin@gmail.com`

Muito obrigado!
