### ISSUE TITLE
StockHistory missing

### ISSUE THREAD

**Issue by mkto20** [Menighin/cei-crawler#38]
Histories that are older than 18 months are not coming on request

**Comment by felipesdias** [comment]
É uma limitação do próprio CEI

![image](https://user-images.githubusercontent.com/24731835/109575850-5fdcee00-7ad1-11eb-9b1c-93b532c7163b.png)

**Comment by Menighin** [comment]
Hi @mkto20 , as Felipe said, this is a limitation from CEI itself. We only have available data until 18 months in the past.
Any other doubts please reopen!
