### ISSUE TITLE
Não realiza o login e não da exception

### ISSUE THREAD

**Issue by evmartinelli** [Menighin/cei-crawler#39]
Pessoal, alguém usou recentemente? 

Não estou tomando erro, mas não está autenticando.

To usando o código de exemplo do tratamento de erro do login.

Valeuu!

**Comment by felipesdias** [comment]
No momento não consigo testar, mas vc pode postar o trecho do código onde vc faz o login e o tratamento de erro?

**Comment by evmartinelli** [comment]
@felipesdias acho que eu comi boa aqui com o sincronismo. Vou fazer mais um teste aqui, qualquer coisa abro dnv.

Valeu demais a resposta rápida!

abs!!
