### ISSUE TITLE
Carteira consolidada.

### ISSUE THREAD

**Issue by thiagodds** [Menighin/cei-crawler#4]
Na [página](https://cei.b3.com.br/CEI_Responsivo/ConsultarCarteiraAtivos.aspx) o CEI disponibiliza as informações consolidadas da carteira. Todos os ativos a quantidade e o valor total da cotação atualizado até o início do dia (acho que atualiza na madrugada).

Sugiro a implementação de um método que pegue essas informações. Apesar do delay de atualização dos valores de cada ativo (uma vez por dia apenas), isso pode facilitar a vida de quem não quer implementar a chamada para uma outra API para pegar a cotação em tempo real. Acredito que existem casos de uso que não precisam de informações em tempo real e podem fazer uso desse método.

**Comment by Menighin** [comment]
Done
