### ISSUE TITLE
Conta em uma corretora com mais de uma carteira

### ISSUE THREAD

**Issue by thiagodds** [Menighin/cei-crawler#44]
Em algumas corretoras é possível comprar ações e usar elas como garantia para outras operações. Para esses casos o CEI separa as ações em duas carteiras diferentes dentro da mesma conta.

Um exemplo para ilustrar:
![image](https://user-images.githubusercontent.com/2293088/115559629-3ac35b00-a28a-11eb-86b1-28762277c2be.png)

Nesse cenário o crawler só pega as informações da primeira carteira.
Acho que seria interessante o crawler conseguir pegar as duas carteiras.

**Comment by Menighin** [comment]
Mergeei o PR e fiz algumas alterações separando os ativos de garantia em outro array.
Valeuzão! 👍
