### ISSUE TITLE
Recebendo erro ao loggar no CEI

### ISSUE THREAD

**Issue by camposbrunocampos** [Menighin/cei-crawler#46]
Fala pessoal, estou recebendo erro de LOGIN_FAILED, porém se loggo a resposta do método de login, parece que o erro está relacionado a essa mensagem:

```2,'The HTTP service located at http://localhost:8053/CEIServicos/GerenciadorGeral.svc is unavailable```
Alguma idéia do que pode estar causando esse erro?

<img width="1420" alt="Screen Shot 2021-05-16 at 15 01 06" src="https://user-images.githubusercontent.com/2911774/118407540-8d105580-b657-11eb-9dbe-ea9a22954773.png">

**Comment by camposbrunocampos** [comment]
Parece que esse erro vem da página que o cei-crawler usa para se loggar:
https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx

Se eu tento usar esta outra no meu navegador, o login é feito com sucesso: 
https://cei.b3.com.br/CEI_Responsivo/

**Comment by Menighin** [comment]
Olá @camposbrunocampos 
Parece que o CEI estava com alguma instabilidade ontem. Outras pessoas me reportaram isso daí.
Aqui ta funcionando normal, resolveu ai pra vc?

**Comment by camposbrunocampos** [comment]
Sim, voltou a funcionar, vou fechar a issue aqui! Obrigado @Menighin
