### ISSUE TITLE
Extrato CETIP

### ISSUE THREAD

**Issue by denisidoro** [Menighin/cei-crawler#47]
Primeiro, parabéns pelo projeto!

Existe alguma previsão para parsear o conteúdo da seguinte URL? https://cei.b3.com.br/CEI_Responsivo/ConsultarExtratoCetip.aspx

Através dela é possível pegar CDBs, LCs, etc.

**Comment by alexandrerocco** [comment]
Eu acho que o problema para essa URL é que ela exporta pra Excel ou PDF apenas. Ao menos aqui pra mim não tem informação direto na tela, então fica um pouco mais complexo.

**Comment by denisidoro** [comment]
Posso escrever a função que vai de uma string CSV pra um JSON object se alguém mais familiarizado com o projeto puder fazer o resto :)

**Comment by denisidoro** [comment]
Na verdade nem é necessário parsear CSV.

Essa página permite, por exemplo, ver todos os CDBs da instituição 0: https://cei.b3.com.br/CEI_Responsivo/ConsultarCertifica.aspx?prdt=CDB&inst=0

**Comment by Menighin** [comment]
Oi pessoal, desculpa a demora... Tenho tido alguns problema pessoais e nao tenho conseguido dar muita atenção.
Pra mim nenhuma das duas telas retorna nenhum dado... Aí nem consigo fazer algo :/ 
Mas acho a idéia boa. Inclusive pras telas que fazem download talvez o ideal seja o crawler nem parsear, mas sim fazer o download do arquivo e o usuário da lib decide se ele vai querer parsear isso ou salvar em algum lugar o arquivo cru.
Se tiverem dificuldades de implementar é só perguntar que eu tento ajudar!

Abraços!
