### ISSUE TITLE
Adicionar suporte a split de ações

### ISSUE THREAD

**Issue by alexandrerocco** [Menighin/cei-crawler#48]
Estava aqui olhando o meu CEI, e um dos eventos que o crawler ainda não suporta é o split/inplit de ações (quando você tem 1 ações e passa a ter 20, ou vice versa).

No CEI, é um bloco de eventos com esse, dentro da seção de proventos:
https://imgur.com/kz7NcVF

Ele aparece muito raramente, mas seria legal ter a informação para poder lembrar quem tem controle em planilhas (ou sistemas) para poder ajustar o preço médio :)

Eu já até implementei a alteração aqui e consegui adicionar um novo array no retorno do método `getDividends()`:
```
"splitEvents": [
    {
        "stock": "B3",
        "stockType": "ON NM",
        "code": "B3SA3",
        "type": "DESDOBRAMENTO DE AÇÕES",
        "date": "2021-05-18T03:00:00.000Z",
        "baseQuantity": 49,
        "factor": 1,
        "destinationCode": "B3SA3",
        "quantity": 98,
        "eventValue": 200,
        "exerciseValue": 0
    }
  ]
```

Caso acham que faz sentido, posso abrir um PR! O que acham?

**Comment by bertoluccimauricio** [comment]
Eu acredito que vale muito a pena

**Comment by Menighin** [comment]
Fala @alexandrerocco !
Acredito ser uma boa sim! Abre o PR sim que a gente analisa :D

**Comment by Menighin** [comment]
Mergeei lá, qualquer coisa avisa! Valeu!
