### ISSUE TITLE
Preço médio.

### ISSUE THREAD

**Issue by thiagodds** [Menighin/cei-crawler#5]
Na [página](https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx) existe uma tabela com o preço médio de compra e preço médio de venda de cada ativo.

Sugiro a implementação de um método que pega essas informações. Com o preço médio de compra é possível o usuário calcular os rendimentos baseado no preço atual do ativo e com o preço médio de venta é possível calcular o lucro/prejuízo do ativo que foi vendido.

**Comment by Menighin** [comment]
Não será implementado pois tendo as negociações, que seria o nível mais baixo, é relativamente facil calcular estes dados consolidados. 
Seria uma "duplicação" de funcionalidade.
