### ISSUE TITLE
Atualização de URL em LastExecutionCrawler

### ISSUE THREAD

**Issue by JuniorEC** [Menighin/cei-crawler#54]
No arquivo [LastExecutionCrawler](https://github.com/Menighin/cei-crawler/blob/master/src/lib/LastExecutionCrawler.js)
tem a seguinte url:
https://investidor.b3.com.br/api/v1/sistema/carga/ultima-execucao

porém a correta é:
https://investidor.b3.com.br/api/sistema/v1/carga/ultima-execucao

**Comment by Menighin** [comment]
Oi Junior, obrigado pelo report
Realmente a nova area logada vem mudando e eu tive que ficar um tempo afastado
Vou tentar reservar um tempo para corrigir esses problemas

**Comment by JuniorEC** [comment]
Se quiser posso fazer um PR

**Comment by Menighin** [comment]
Opa, consegui um tempinho e corrigi essa e a URL de checagem de Login, Junior.
Todos os testes passaram. Dá uma conferida aí se a `v3.0.1` tá certinha pra vc tb.
Qualquer coisa reabre,
Abs
