### ISSUE TITLE
Problema: headless = true

### ISSUE THREAD

**Issue by fredericocotrim** [Menighin/cei-crawler#6]
Com headless = true não funciona.

**Comment by Menighin** [comment]
Opa, joia?
Poderia dar um exemplo do que você ta tentando fazer?
E o que seria "nao funciona"? Crasha? Roda mas sem abrir o browser?

**Comment by fredericocotrim** [comment]
Opah... blz!?

Com headless ocorre timeout. Acabei de descobrir o problema... não sei se é só no Windows 7 mas... a solução foi adicionar nas opções:

args: ['--proxy-server="direct://"', '--proxy-bypass-list=*']

Conforme: https://github.com/puppeteer/puppeteer/issues/2391

**Comment by Menighin** [comment]
GG
Não parece ser relacionado com o `cei-crawler` então vou fechar
