### ISSUE TITLE
Tempo para Login

### ISSUE THREAD

**Issue by fpmacedo** [Menighin/cei-crawler#7]
Boa tarde, no momento do login apos 35 segundos considera que o login falhou, mas algumas vezes notei que o site da B3 demora mais que esse tempo para retornar a requisicao de login, talvez seria interessante incluir essa variavel como customizada juntamente com o ceiCrawlerOptions, para que em casos onde o retorno demore a aconter nao aconteca esse erro, mesmo sem ser um erro de login.

Trecho de codigo a que me refiro:
```
{
                id: 'fail',
                pr: this._page.waitFor(35000) // After 35s, consider the login has failed
            }
```

Valeu!

**Comment by Menighin** [comment]
Opa, oi @fpmacedo 
É uma boa sim. To meio sem tempo esses dias mas vou tentar.
Uma coisa que notei é que mais a noite (22h+) ou nos fins de semana o site do CEI fica impossivel.
Eu nem consigo publicar versao do pacote porque os testes ficam quebrando no Travis... Imagino que role alguma manutenção ou algo assim...
Abraço

**Comment by Menighin** [comment]
Implementado na versao `0.2.1`

**Comment by fpmacedo** [comment]
Muito bom cara! Que bom ver que você segue tocando o projeto.
