### ISSUE TITLE
Erro ao buscar dados da carteira

### ISSUE THREAD

**Issue by matheuspcunha** [Menighin/cei-crawler#9]
Olá!

Não tenho conseguido utilizar o getWallet(), ele chega a logar no CEI, começa a buscar os dados da carteira porém da erro no meio. Segue o log completo com o erro:

```
Logging at CEI...
Selecting institution 308 - CLEAR CORRETORA - GRUPO XP (308)
Selecting account 2129
Processing wallet data
Error ReferenceError: data is not defined
    at Function._callee2$ (/Users/matheuscunha/Documents/Projetos/cei/node_modules/cei-crawler/app.js:1:20417)
    at tryCatch (/Users/matheuscunha/Documents/Projetos/cei/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/matheuscunha/Documents/Projetos/cei/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/matheuscunha/Documents/Projetos/cei/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/matheuscunha/Documents/Projetos/cei/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/matheuscunha/Documents/Projetos/cei/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Menighin** [comment]
Opa, vo dar uma olhada Matheus! Obrigado!

**Comment by Menighin** [comment]
@matheuspcunha rodei aqui com a minha conta do CEI e funcionou. Sua conta deve ter algum edgy case que nao tem na minha aí nao to pegando.
Faz um favor pra mim?

- Loga no CEI
- Vai na Carteira
- Seleciona a sua corretora e conta e manda filtrar, de forma que apareçam os resultados.
- Abra o seu inspect do navegador e vê se os códigos abaixo retornam dados:

```
var stockTBody= document.querySelector('#ctl00_ContentPlaceHolder1_rptAgenteContaMercado_ctl00_rptContaMercado_ctl00_rprCarteira_ctl00_grdCarteira tbody');
var stockRows = stockTBody.rows;
console.log(strockRows);

var treasuryTBody= document.querySelector('#ctl00_ContentPlaceHolder1_rptAgenteContaMercado_ctl00_rptContaMercado_ctl00_trBodyTesouroDireto tbody');
var treasuryRows = treasuryTBody.rows;
console.log(treasuryRows);
```

E me diz uma coisa, nessa carteira vc tem ações? E Tesouro Direto?

Abs

**Comment by matheuspcunha** [comment]
@Menighin, para esta corretora que esta no log em especifico não tenho Tesouro apenas Ações. Tenho Tesouro na carteira sim, mas em outra corretora.

Fiz conforme você disse e para esta corretora que só tem Ações retornou os dados porém deu erro apontando que o Tesouro é nulo
![Captura de Tela 2020-06-18 às 22 23 04](https://user-images.githubusercontent.com/22895936/85086899-5c5b3e00-b1b2-11ea-9f20-1babd8a9a3c7.png)

Para a corretora que tem apenas o Tesouro, foi o mesmo, ele aparece os dados do Tesouro mas aponta nulo para as ações.

**Comment by Menighin** [comment]
Matheus achei aqui... Vc tá rodando com `trace: true` e de fato tinha um bug em um dos condicionais pra logar... Coisa boba mesmo... O fix ta disponivel na versao `0.2.2` (subindo agora). Testa pfv e me fala se ficou gg

**Comment by matheuspcunha** [comment]
@Menighin, agora funcionou! 

Só percebi um gargalo bem grande, de mais ou menos uns 20s quando passa pelas corretoras que não contêm nenhum investimento (Ações ou Tesouro), porém as que contém investimento não demoram nem 1s para processar os dados.
Como eu tenho 4 corretoras sem nada, tem demorado em média 1m20s toda a request pra buscar a Carteira.

Agora não sei se isso pode ser algo no _cei-crawler_ ou no próprio CEI

Obrigado.

**Comment by Menighin** [comment]
Hummm pode ser no CEI pq agora parece que ele ta lento, até quebrou na hora de subir.
Quando vc faz a busca em uma corretora que nao tem nada, o que é carregado na pagina? Conseguiria me enviar um print escondendo suas informações, claro?

**Comment by matheuspcunha** [comment]
@Menighin, é isso que aparece:

![Sem Título](https://user-images.githubusercontent.com/22895936/85186204-1794dd00-b26e-11ea-9344-a5b32b020a0a.png)

**Comment by Menighin** [comment]
@matheuspcunha acho que amanha vo ter um tempo pra mexer nisso.
Vc testou mais vezes pra ver se era intermitencia do CEI?

**Comment by matheuspcunha** [comment]
@Menighin, testei sim. Vim testando durante esses dias pra ver se poderia ser instabilidade no CEI mesmo, mas acredito que não, pois teve o mesmo comportamento independente do horário/dia 😞

**Comment by Menighin** [comment]
Perfeito... É o wait do puppeteer entao... Quando nao tem nenhuma ação / tesouro na carteira ele nao é trigado...
Eu parei tarde mas ja identifiquei e vou corrigir asap 👍

**Comment by matheuspcunha** [comment]
Opa @Menighin, muito obrigado! 🥳

**Comment by Menighin** [comment]
@matheuspcunha acabei de publicar a `0.2.3`
Atualiza ai e me fala se resolveu pfv!

**Comment by matheuspcunha** [comment]
Funcionou perfeitamente, @Menighin! 
Valeu demais!
